### ISSUE TITLE
Enhancements suggestions for a readable Repo

### ISSUE THREAD

**Issue by evya1** [barakdiker123/lea_inplementation_algo#1]
HI @barakdiker123 , 

I found this very interesting, but It's a bit hard to navigate through. 
Here are few key tips for a readable repo:

1. I suggest adding a markdown file in the main dir of the repo. 
2. I would suggest remake the main branch of this repo which is `development` to `main`.
3. Name the python file with significant names, for example if  `example_code_example1.py` has an algorithm in it I would have rename it to `name_of_the_algorithm.py`. And if you want to provide a user a friendly file as a quick start for the repo I would create another file like `quickstart.py`. 

Hope you find this tips useful.

**Comment by barakdiker123** [comment]
Hello 

- [ X ]  I suggest adding a markdown file in the main dir of the repo.

- [ X ] I would suggest remake the main branch of this repo which is development to main.

- [ X ] Name the python file with significant names, for example if example_code_example1.py has an algorithm in it I would have rename it to name_of_the_algorithm.py. And if you want to provide a user a friendly file as a quick start for the repo I would create another file like quickstart.py.

I have did the following instructions , hopefully the repo code would be better now 
please note that the website and the markdown have the same content

**Comment by barakdiker123** [comment]
maybe later I would add a quickstart which would help navigate between different heuristics 

Barak
